// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4k5VUvYN9ByL8a1GrrWDBZ
// Component: U41vdRq-D0
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_plume_plasmic_kit_leos_wip.module.css"; // plasmic-import: 4k5VUvYN9ByL8a1GrrWDBZ/projectcss
import sty from "./PlasmicBoom.module.css"; // plasmic-import: U41vdRq-D0/css

export const PlasmicBoom__VariantProps = new Array();

export const PlasmicBoom__ArgProps = new Array("_new");

function PlasmicBoom__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <input
        data-plasmic-name={"textbox"}
        data-plasmic-override={overrides.textbox}
        className={classNames(defaultcss.input, sty.textbox)}
        placeholder={"Some placeholder"}
        size={1}
        type={"text"}
        value={"Some value"}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "textbox"],
  textbox: ["textbox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBoom__ArgProps,
      internalVariantPropNames: PlasmicBoom__VariantProps
    });

    return PlasmicBoom__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBoom";
  } else {
    func.displayName = `PlasmicBoom.${nodeName}`;
  }
  return func;
}

export const PlasmicBoom = Object.assign(
  // Top-level PlasmicBoom renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textbox: makeNodeComponent("textbox"),
    // Metadata about props expected for PlasmicBoom
    internalVariantProps: PlasmicBoom__VariantProps,
    internalArgProps: PlasmicBoom__ArgProps
  }
);

export default PlasmicBoom;
/* prettier-ignore-end */
